### PR TITLE
exo-clean cleans containers

### LINKED ISSUE #320: "exo clean" should remove existing Docker containers for the app
> When there are running Docker containers that break "exo run"
I want to be able to stop and remove them cleanly using "exo clean"
So that I can start my application normally without having to google how to remove Docker containers manually.

#### Rules:
- running "exo clean" stops and removes all Docker containers that are listed in application.yml 
- running Docker containers are stopped by running `docker stop <container names>`
- stopped Docker containers are removed by running `docker rm <container names>`

#### Notes:
This fixes this error:
```
exo-run  Creating web ... error
               exo-run  

               exo-run  ERROR: for web  Cannot create container for service web: Conflict. The container name "/web" is already in use by container    "f266b77ba98a3212d1ad727c1659195136c6c4968ad92c0961d4afe20087b06a". 
                               You have to remove (or rename) that container to be able to reuse that name.
```

### PR DESCRIPTION
**Pull request by hugoesthere**
resolves https://github.com/Originate/exosphere/issues/320

### CODE REVIEW

File: test_helpers/clean_feature_context.go [hunk 1]
```diff
@@ -49,6 +90,74 @@ func CleanFeatureContext(s *godog.Suite) {
...
+		}
+		testContainerProcess = execplus.NewCmdPlus("docker-compose", "-p", testNetwork, "create")
+		testContainerProcess.SetDir(path.Join(appDir, "service", "tests", "tmp"))
+		return testContainerProcess.Start()
+	})
+
+	s.Step(`^my machine has running third party containers$`, func() error {
+		thirdPartyContainerProcess = execplus.NewCmdPlus("docker", "run", "--name", thirdPartyContainer, "--rm", "alpine", "sleep", "20")
+		err := thirdPartyContainerProcess.Start()
+		time.Sleep(2500 * time.Millisecond)
```
Comment (charlierudolph) [inline test_helpers/clean_feature_context.go]: Whats the need for the sleep here?

File: test_helpers/clean_feature_context.go [hunk 2]
```diff
@@ -49,6 +90,74 @@ func CleanFeatureContext(s *godog.Suite) {
...
+		return err
+	})
+
+	s.Step(`^it removes application and test containers$`, func() error {
+		hasNetworkBool, err := hasNetwork(dockerClient, appNetwork)
```
Comment (charlierudolph) [inline test_helpers/clean_feature_context.go]: Thoughts on renaming `hasNetworkBool` -> `hasAppNetwork`. Similar for `hasTestNetwork`

File: src/application/clean.go [hunk 3]
```diff
@@ -0,0 +1,63 @@
...
+	}
+	serviceData := config.GetServiceData(appConfig.Services)
+	for _, data := range serviceData {
+		dockerComposeFile := path.Join(appDir, data.Location, "tests", "tmp", "docker-compose.yml")
+		exists, err := util.DoesFileExist(dockerComposeFile)
+		if err != nil {
+			return err
+		}
+		if exists {
+			composeProjectName := fmt.Sprintf("%stests", composebuilder.GetDockerComposeProjectName(appDir))
```
Comment (charlierudolph) [inline src/application/clean.go]: This is duplicated in `src/cmd/test.go`. Can we extract this into a function somewhere. Could be something like `GetTestsDockerComposeProjectName`?

File: src/application/clean.go [hunk 4]
```diff
@@ -0,0 +1,63 @@
...
+	if exists {
+		composeProjectName := composebuilder.GetDockerComposeProjectName(appDir)
+		_, err = compose.KillAllContainers(compose.BaseOptions{
+			DockerComposeDir: path.Join(appDir, "tmp"),
+			LogChannel:       logChannel,
+			Env:              []string{fmt.Sprintf("COMPOSE_PROJECT_NAME=%s", composeProjectName)},
+		})
+		if err != nil {
+			return err
+		}
```
Comment (charlierudolph) [inline src/application/clean.go]: There appears to be a good amount of duplication here between does the docker compose file exist and killing all containers. Can we dry that up a bit? Maybe a function that takes in the `dockerComposeDir` and `composeProjectName`

File: src/cmd/clean.go [hunk 5]
```diff
@@ -25,12 +29,26 @@ var cleanCmd = &cobra.Command{
 		if err != nil {
 			panic(err)
 		}
-		fmt.Println("removed all dangling images")
+		logger.Log("exo-clean", "removed all dangling images")
```
Comment (charlierudolph) [inline src/cmd/clean.go:33]: This could be `logChannel <- "removed all dangling images"`

File: test_helpers/clean_feature_context.go [hunk 6]
```diff
@@ -49,6 +90,74 @@ func CleanFeatureContext(s *godog.Suite) {
...
+		appContainerProcess = execplus.NewCmdPlus("docker-compose", "-p", appNetwork, "up")
+		appContainerProcess.SetDir(path.Join(appDir, "tmp"))
+		err := appContainerProcess.Start()
+		if err != nil {
+			return err
+		}
+		testContainerProcess = execplus.NewCmdPlus("docker-compose", "-p", testNetwork, "up")
+		testContainerProcess.SetDir(path.Join(appDir, "service", "tests", "tmp"))
+		err = testContainerProcess.Start()
+		time.Sleep(2500 * time.Millisecond)
```
Comment (charlierudolph) [inline test_helpers/clean_feature_context.go]: Why is this sleep needed?

File: test_helpers/clean_feature_context.go [hunk 7]
```diff
@@ -49,6 +90,74 @@ func CleanFeatureContext(s *godog.Suite) {
...
+	s.Step(`^my machine has stopped application and test containers$`, func() error {
+		appContainerProcess = execplus.NewCmdPlus("docker-compose", "-p", appNetwork, "create")
+		appContainerProcess.SetDir(path.Join(appDir, "tmp"))
+		err := appContainerProcess.Start()
+		if err != nil {
+			return err
+		}
+		testContainerProcess = execplus.NewCmdPlus("docker-compose", "-p", testNetwork, "create")
+		testContainerProcess.SetDir(path.Join(appDir, "service", "tests", "tmp"))
+		return testContainerProcess.Start()
```
Comment (charlierudolph) [inline test_helpers/clean_feature_context.go]: This and the previous step seep quite similar with the only difference being "up" and "create". Can we dry that up?

File: test_helpers/clean_feature_context.go (hunk 6 above)
Comment (hugoesthere) [reply test_helpers/clean_feature_context.go]: To give the containers time to "start up". I think there was a point in the test between when `docker-compose up` has been executed and the actual containers show up as running in `docker ps`

File: test_helpers/clean_feature_context.go (hunk 1 above)
Comment (hugoesthere) [reply test_helpers/clean_feature_context.go]: Same reason as above.

File: test_helpers/clean_feature_context.go (hunk 6 above)
Comment (charlierudolph) [reply test_helpers/clean_feature_context.go]: Can we wait for them to show up in `docker ps` then? I'd prefer we have deterministic waits instead of a time we hope is long enough

File: src/cmd/clean.go (hunk 5 above)
Comment (hugoesthere) [reply src/cmd/clean.go:33]: I think we avoided using logChannels here because that gave us a problem where the process would finish before all statements were printed.

Comment (charlierudolph) [reply src/cmd/clean.go:33]: True, nevermind good as is

**Review by charlierudolph — APPROVED** [review]
Good to merge when green (or when confident nothing broke as the builds have been failing every now and then for me)
