### PR TITLE
Print failed test services

### LINKED ISSUE #738: exo test: list what services fail
When testing all services and one fails, it outputs:
```
1 tests failed
```
This requires searching for what tests failed. Instead, lets output the following in red:
```
The following services failed:
service-a
service-b
```
Also update the `all tests passed` message to be green

### PR DESCRIPTION
**Pull request by hugoesthere**
resolves https://github.com/Originate/exosphere/issues/738

### CODE REVIEW

**Review by charlierudolph — APPROVED** [review]

File: src/application/tester/tester.go [hunk 1]
```diff
@@ -42,17 +43,22 @@ func TestApp(appContext types.AppContext, writer io.Writer, mode composebuilder.
...
 		return types.TestResult{
 			Passed: true,
 		}, nil
 	}
-	util.PrintSectionHeaderf(writer, "%d tests failed\n\n", numFailed)
+	red := color.New(color.FgRed)
+	red.Fprint(writer, "The following tests failed:\n")
+	for _, failedTest := range failedTests {
+		red.Fprintln(writer, failedTest)
+	}
```
Comment (charlierudolph) [inline src/application/tester/tester.go]: To combat the lint failure, can we extract printing the results to its own function?

File: src/application/tester/tester.go [hunk 2]
```diff
@@ -43,18 +44,34 @@ func TestApp(appContext types.AppContext, writer io.Writer, mode composebuilder.
...
+	var err error
+	if len(failedTests) == 0 {
+		green := color.New(color.FgGreen)
+		_, err = green.Fprint(writer, "All tests passed\n\n")
+		if err != nil {
+			return err
+		}
+	}
+	red := color.New(color.FgRed)
+	_, err = red.Fprint(writer, "The following tests failed:\n")
```
Comment (charlierudolph) [inline src/application/tester/tester.go]: This error value is unchecked

File: src/application/tester/tester.go [hunk 3]
```diff
@@ -43,18 +44,34 @@ func TestApp(appContext types.AppContext, writer io.Writer, mode composebuilder.
...
-			Passed: true,
-		}, nil
+	err = printResults(failedTests, writer)
+	return types.TestResult{
+		Passed: len(failedTests) == 0,
+	}, err
+}
+
+func printResults(failedTests []string, writer io.Writer) error {
+	var err error
```
Comment (charlierudolph) [inline src/application/tester/tester.go]: I don't think this needs to be defined up here

**Review by charlierudolph — APPROVED** [review]
